apiVersion: v1
kind: Namespace
metadata:
  name: svcquarkusdemo
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: svcquarkusdemo
  name: postgres-configuration
  labels:
    module: heros
    app: postgres
data:
  POSTGRES_DB: herosdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: passw0rd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: svcquarkusdemo
  name: postgres-deploy
  labels:
    module: heros
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        envFrom:
        - configMapRef:
            name: postgres-configuration
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgresql
  namespace: svcquarkusdemo
spec:
  ports:
  - nodePort: 31825
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  type: LoadBalancer
        